const client2025FList = `chuchi.arevalo@sparkbusinessacademy.com
debsadams@gmail.com
pokuelse@gmail.com
sharonadu2@gmail.com
eakhtarzandi@nationaljournal.com
aldersonkelly@hotmail.com
skaleni@gmail.com
rend.almondhiry@gmail.com
lisamazer@hotmail.com
csladkin@hotmail.com
ialvarez@alvarezmartinezlaw.com
famerasinghe@gmail.com
felixcichlid@gmail.com
robamedegracia@gmail.com
sofia.ammor@gmail.com
email4amyrose@aol.com
christieanastasio@gmail.com
andersonjana010@gmail.com
misha.m.anderson@icloud.com
col.andrews@gmail.com
camilleandrews@gmail.com
munn@aneja.us
anjali@mytonomy.com
kansary@gmail.com
mashin@gmail.com
hatallah@broadoak.com
rolaate@gmail.com
shopping@atoyebi.com
chata.atuanya@mcpsmd.net
daugust@msn.com
gregg.avitabile1@verizon.net
thegonzalezfamilia@gmail.com
fatima.awad@gmail.com
endaleayano@yahoo.com
tell.aidyn@gmail.com
azadeh.eshaghi@gmail.com
taranehmohseni@gmail.com
jsba3@yahoo.com
sbyeboah@gmail.com
gshock75@mac.com
geetanjali_01@yahoo.com
lucianaf@iadb.org
bri.barker@gmail.com
jodibarr@gmail.com
aw.bartleman@verizon.net
anganab@gmail.com
abasuzych@gmail.com
alexisb03@gmail.com
susbathalon@gmail.com
bcastuera@gmail.com
pascal@bethesdascholars.com
mandabellamy@gmail.com
shahiar@msn.com
atbenjamin76@gmail.com
jnesterak@gmail.com
shari72@aol.com
miller.maya@gmail.com
jenbester@gmail.com
sheetalandamar@gmail.com
ninabhatt2235@gmail.com
lmontenegro@eya.com
as-cirak@live.de
216916@mcpsmd.net
marisolblanchard@gmail.com
jboccanera1@gmail.com
boesche99@verizon.net
cbogyo@yahoo.com
kibibi_potts@yahoo.com
mborrus@aol.com
mboshnick@gmail.com
dora_gmati@yahoo.com
elizabethbarksdaleboyle@gmail.com
celestebraschi@gmail.com
katiebrebbia@gmail.com
seanbrebbia@gmail.com
lizbrenner67@gmail.com
jamiebresnick@gmail.com
brownhowiler@verizon.net
thebrownings44@gmail.com
jillrowlison@gmail.com
amysquirebuckley@yahoo.com
debra@cofs.org
mjbuening@gmail.com
yan_bui@yahoo.com
eburton@crowell.com
amelia.risner@gmail.com
butlerjill1@gmail.com
alejandro91433@gmail.com
colyn67@hotmail.com
patricia.caira@yahoo.com
heathercameron@mac.com
jcameron3@hushmail.com
jilldcampbell@gmail.com
patricialcuellar@yahoo.com
cynthiacanelas@gmail.com
patrick_j_capuano@mcpsmd.org
bob.carey@empire-capitol.com
tjandcarolinecarlin@gmail.com
carolina.leivacl@gmail.com
mccarrea@gmail.com
jamiee@bethesdascholars.com
tiffreneh@hotmail.com
anacerna314@gmail.com
chai.shenoy@gmail.com
mihyun78@gmail.com
sbcharles@comcast.net
lin.chenboeckle@googlemail.com
lin.chenboeckle@gmail.com
amsurdo@gmail.com
lulu.cheng@gmail.com
ann.chernicoff@gmail.com
angela.chiang@gmail.com
crazyhindoo@gmail.com
xinli1999@hotmail.com
tuana.cirak08@gmail.com
h_elgin@yahoo.com
colledaninorma@gmail.com
mscasad@hotmail.com
tkcolonna@yahoo.com
suntaree.combs@gmail.com
jgc3.iphone@gmail.com
amy_laurence@hotmail.com
laurenacorsini@gmail.com
bego.cortina@me.com
ccosta00@gmail.com
bcotlear@gmail.com
charlottehcox@gmail.com
coyne.christopher@gmail.com
kcronin08@gmail.com
croppbe@live.com
lisacrum007@gmail.com
dana@soldbydana.com
priscillacruz@live.com
christophercurry10@gmail.com
marquezdagan@gmail.com
sallyyingdai@hotmail.com
terena.daniel@gmail.com
emily@emilykopp.com
janiceldarcy@gmail.com
ydatta1@gmail.com
natashaannedavid@yahoo.co.uk
davischristines@yahoo.com
arsalad@yahoo.com
dsmi575@gmail.com
thedegroffs@gmail.com
bridgetdelellis@gmail.com
niki.engle@gmail.com
jldeppe@gmail.com
malcolmmdesouza@gmail.com
marendevereaux@gmail.com
ndever1979@gmail.com
amanda.dickson@gmail.com
telanders@gmail.com
wallyrules@verizon.net
bdolven@yahoo.com
bethdonaldson@verizon.net
sheba.douoguih@gmail.com
sherimarco@gmail.com
whitwhitd@icloud.com
staceydussault@gmail.com
jdzowela@icloud.com
susan.eagle@yahoo.com
eileen.lee1101@gmail.com
sadie.a.eisenberg@gmail.com
stacey.eisenstein@gmail.com
jann.elliott@gmail.com
erenglish621@gmail.com
narcissush72@yahoo.com
evanewmark@gmail.com
margaret@margareteverson.com
joanneandjosh@yahoo.com
joshfaber@hotmail.com
mfairbanks3@gmail.com
kelly@janefairweather.com
nfakhari777@gmail.com
loocyloo@gmail.com
craig.fanning@gmail.com
hgfarrell@yahoo.com
kelliebalster@hotmail.com
federicamichetti@ymail.com
adrianaferrer@gmail.com
susannah.files@gmail.com
dfflowers7@gmail.com
arianafoley@gmail.com
bannisterrenee@aol.com
brianpoefrank@me.com
kimberlybfrank@yahoo.com
tricia@fredley.com
lauramar001@gmail.com
hffrench@gmail.com
juliebfritts@gmail.com
kathygoldberg@hotmail.com
cgabarain@gmail.com
lauragaensly@gmail.com
sonigar@hotmail.com
patmgaviria@gmail.com
jaclyngeller@gmail.com
heather.gerth@verizon.net
gargee415@gmail.com
gibbons.crista@gmail.com
jawariagilani@gmail.com
natalie.gillberg@gmail.com
lgilpatric@gmail.com
susan.goldenson@gmail.com
aliciagoldin@gmail.com
dgoldseker@gmail.com
mlgolemon@gmail.com
finnjcc@gmail.com
gonzalez7856@icloud.com
asg5018@gmail.com
laurie.goodwin@croplife.org
mg@megangray.com
cg@carysgray.com
michelle.d.greenberg@gmail.com
marcia@artfuldiscoveries.com
gkrewe@gmail.com
roxana.grieve@gmail.com
marina.lordan@gmail.com
vineetausa@gmail.com
acmhv5@gmail.com
ruhana.hafiz@gmail.com
ingramk11@gmail.com
sanahaneef@gmail.com
sophie@bethesdascholars.com
fariha_haque@yahoo.com
ayako0101@hotmail.com
zhasnain@worldbank.org
jaconihawe@gmail.com
hugeneres@aol.com
mhebb1350@yahoo.com
khefling@gmail.com
tmhekimian@gmail.com
pjhny2012@yahoo.com
alma79@gmail.com
alison.hills@gmail.com
wadiehobson@gmail.com
jgracehochman@gmail.com
hillbillisa164@gmail.com
ehogan23@stoneridgeschool.org
forgab@gmail.com
holibaugh@hotmail.com
julieatenney@aol.com
valerie@hollisweb.net
maureen.h29@gmail.com
mkholohan@gmail.com
masonholstein@icloud.com
ahudsondc@gmail.com
david@davidhughes.ca
jhuguely@gmail.com
ximeiq@hotmail.com
ilanasimonesaltzbart@gmail.com
milias1977@gmail.com
shai_ingber@yahoo.com
melissaingber@hotmail.com
inma1805@yahoo.com
ishiharasakiko34@gmail.com
leifjackson@gmail.com
petraejacobs@gmail.com
rosenylan@yahoo.com
annkjay1@gmail.com
estelle.d.jean@gmail.com
pretzel1970@verizon.net
dabney.doswell@gmail.com
christina.jewett@gmail.com
sdjofferion@gmail.com
jean.j.joh@gmail.com
johnlam214@gmail.com
sarahej00@gmail.com
sarahmoorejohnson@me.com
cabinjohnsons@gmail.com
jordan.jena000@gmail.com
yogesh.joshi@gmail.com
manila.pradhan@gmail.com
shareen.joshi@gmail.com
huijeong_hahm@yahoo.com
p_jurado@hotmail.com
mjustdc@msn.com
corfumaggie08@gmail.com
kanlimin@gmail.com
rachelkasprik@gmail.com
anjali.kataria@gmail.com
dhara167@yahoo.com
meetakaursreimagine@gmail.com
kyokokelly@gmail.com
mkerwinm@yahoo.com
mkhaishgi@gmail.com
angelak38@hotmail.com
eaglesphilly@gmail.com
poojakhera@gmail.com
lilliankidane1@gmail.com
skattakuzhy@yahoo.com
mlkilbride@yahoo.com
emily.kimberly@gmail.com
kimberlyav@gmail.com
simonaking71@gmail.com
robking.king@gmail.com
rachel.t.kirby@gmail.com
rweissberger@gmail.com
seaklein@gmail.com
estherhuhkoi@gmail.com
vuk.koprivica@gmail.com
clw14@cornell.edu
cbkress@icloud.com
dgdgbd@gmail.com
caseynkulnis@gmail.com
katemccarthy1971@gmail.com
gopirama@gmail.com
sk@onestreet.one
lacey1@gmail.com
mkuzee@gmail.com
ilam1029@yahoo.com
aline5709@yahoo.com
sml73@ymail.com
smlars7733@gmail.com
akolattin@yahoo.com
lawsan484@gmail.com
sofialazarus207@gmail.com
rebeccaleavey@gmail.com
hkkim72@gmail.com
yiechia@hotmail.com
lenora.till@gmail.com
absolutelyleonard@gmail.com
joanneleong9@gmail.com
iletko26@kentdenver.org
hletko@gmail.com
mlevi411@gmail.com
lkglevinson@gmail.com
liyan11733@gmail.com
liao.hueilin@gmail.com
alina.liberska2000@gmail.com
lida.oum@gmail.com
susan.limb@gmail.com
linikujp@gmail.com
jodilipson2@gmail.com
holly.lipton@gmail.com
lizamorris1@gmail.com
elizabeth.lizama@gmail.com
london.jk@gmail.com
jeannielorenz@yahoo.com
carlos.lozada@nytimes.com
kslucas@gmail.com
tinalucas2012@gmail.com
dblukken@gmail.com
cherylluria@gmail.com
chothuzarlwin@gmail.com
adamericlyons@gmail.com
jess@macpherson.tv
supriyamadhavan@hotmail.com
ceciliamaggi@hotmail.com
ssaimaamalik@gmail.com
zieranaseer@hotmail.com
pmalik@worldbank.org
nursefine10@gmail.com
jacob71709@gmail.com
mayamanian@gmail.com
loiewmann@gmail.com
marcegenomica@gmail.com
mcleanpsychotherapy.markwood@gmail.com
aisham.martin@gmail.com
maite00@gmail.com
rmattick@outlook.com
yates.maureen@gmail.com
acmaurice@gmail.com
akmayo5@verizon.net
lorennejulia@aol.com
hollymm17@gmail.com
klmcgovern@gmail.com
georgiamc@gmail.com
solina.mehilli@gmail.com
soosan_13@hotmail.com
melliyross@hotmail.com
jedmeline@yahoo.com
mdmeline@yahoo.com
mmeline2@yahoo.com
nuam2010@gmail.com
bmencher@gmail.com
karla.mendoza@gdpteam.com
pammercer8@gmail.com
danisafreiremerino@yahoo.com.br
tlomeyer@gmail.com
hsmichaels@yahoo.com
marisa.michnick@gmail.com
khmilhollin@gmail.com
rsmiller99@gmail.com
hminato@gmail.com
t.minor30@yahoo.com
miriam.mintzer@gmail.com
selerity@aol.com
surajita2004@yahoo.com
meliya33@outlook.com
aigul_m@hotmail.com
grecofamily19@gmail.com
kerrymoore@aol.com
ccmorton11@gmail.com
allisonemoses@gmail.com
maddyanderic2@gmail.com
eshel7@aol.com
naramd6@gmail.com
bhagyamurali@gmail.com
murrayaya@hotmail.com
ermusselman@gmail.com
adriana.naim@gmail.com
renukanair@hotmail.com
dcelena@me.com
veronicanavaso@gmail.com
nazarovaelena730@gmail.com
ymengst@gmail.com
5windnsea@gmail.com
thais.n.newton@gmail.com
trinhnguyen2007@gmail.com
gissel@dcbusinessadvisor.com
hannah.s.nielsen@gmail.com
evateamdc@gmail.com
laurabnjanga@gmail.com
noonan.stacey@gmail.com
atash4@gmail.com
anunez@worldbank.org
nkgoraya@gmail.com
lauraemmettoconnor@gmail.com
amieo1620@gmail.com
avaohana@gmail.com
pjohara@yahoo.com
duzyolfamily3@gmail.com
oliveguo2024@gmail.com
scohara11@hotmail.com
egurmai@hotmail.com
momeara@appent.com
injeoueslati@gmail.com
gozenci@gmail.com
valpeco@yahoo.com
russellpalanzo@gmail.com
thefamilypardo@gmail.com
emiliapd@gmail.com
sethpooja@yahoo.com
llgg23@hotmail.com
skimmyaloha@gmail.com
alanparsa@yahoo.com
maulin111@gmail.com
chai.desai@gmail.com
anujappatel@gmail.com
debrajoy@gmail.com
spelmoter@yahoo.com
chathurisp@gmail.com
spetullo@gmail.com
dpetullo@gmail.com
pikemartina04@gmail.com
ajapittman@gmail.com
nancydimag@gmail.com
jponcehuerta@gmail.com
adlapontes@gmail.com
santiagoporta@yahoo.com
caitcooper@hotmail.com
lynnrpowers@hotmail.com
lisab428@aol.com
iramqazi@gmail.com
betoeq72@gmail.com
nquist25@gmail.com
esherison@verizon.net
rvajpeyi@gmail.com
ramos.jessica00@gmail.com
rana_wahby@yahoo.com
jenrancilio@gmail.com
dafna.hochman@gmail.com
rrandall0819@gmail.com
nikirateshtari@gmail.com
rsundin@gmail.com
mertmason@gmail.com
glo3386@yahoo.com
scottreiter@gmail.com
meredithrender@yahoo.com
revzans@gmail.com
mireyabrogan@gmail.com
valquiriarey@gmail.com
ana@anareyes.com
mvreynolds77@gmail.com
onlykidsgr@gmail.com
viviankeiko@hotmail.com
manuluca2010@gmail.com
stacylrich@gmail.com
shararich51@gmail.com
haileykh@aol.com
jutersorky@gmail.com
nkowens@gmail.com
jhnritchie@yahoo.com
rrivasrogers@xtrategycenter.com
jennyrockrocks@gmail.com
kirsten.roddy@gmail.com
irmelguizo@yahoo.com
sarahfraidin@gmail.com
hrohee@gmail.com
courtney.k.rose@gmail.com
mljrose19@yahoo.com
wendyrosensweig@gmail.com
vroshchanka@yahoo.com
pjr_mailing@yahoo.com
nilmini.rubin@gmail.com
illanacindy@aol.com
allison.russo@yahoo.com
janesmith@gmail.com
carrie.safford@gmail.com
rachels-98@hotmail.com
saimasong@gmail.com
carolinasaizar@gmail.com
slsals@yahoo.com
samasuzy@icloud.com
deannsanders03@gmail.com
barhoumi.sandra@gmail.com
msangeorge@gmail.com
schelala@gmail.com
amyscharpf1@gmail.com
ejs480@yahoo.com
stephanie.schuerman@gmail.com
abbyschulten@gmail.com
cslavin@gmail.com
kbschwed@gmail.com
jessica.schweighofer@gmail.com
amyscofield@gmail.com
roysehgal@gmail.com
sarkasengezener@gmail.com
debbiesenker@gmail.com
jsenne@gmail.com
lauraseus@gmail.com
slsfondo@icloud.com
sshah1999@gmail.com
heba.shamsa@outlook.com
hmshamseldin@outlook.com
marc@mcbrideres.com
avi.guh@gmail.com
shigeshige2525@gmail.com
eileen_shih@yahoo.com
sanazshojaie@hotmail.com
sarah.sicherman@gmail.com
cdd446@mail.harvard.edu
miris_nascimento@live.com
lgreller@yahoo.com
lrsilvis@gmail.com
bettysimonogan@gmail.com
ecsingh0257@gmail.com
leher.singh@gmail.com
leher.singh.nus@gmail.com
nadiakhan01@gmail.com
chsk147@icloud.com
lauraskolnik@gmail.com
meghan.arbegast@nih.gov
etscesnas@gmail.com
harrisonsolomon@hotmail.com
jobe.solomon@gmail.com
ldsolomon@gmail.com
soueid.erica@gmail.com
annespeca@gmail.com
ispero@erols.com
emmastarr13@gmail.com
jenna10948@gmail.com
gsteis@comcast.net
jgstember@gmail.com
maliaartist@yahoo.com
juliastew@gmail.com
mountainbranch.1@gmail.com
subasiselin@gmail.com
mariannesullivanmd@icloud.com
amelia.garrett@gmail.com
drdeepa.s@gmail.com
susanmitchellblavin@gmail.com
sa_swan@yahoo.com
hswisher@hotmail.com
behnaz4@yahoo.com
atallone@gmail.com
timkoclan@gmail.com
enku1629@hotmail.com
d_tekin@yahoo.com
tihitina@hotmail.com
thatch_sj@yahoo.com
tactile_launder_0h@icloud.com
tilghmansca@icloud.com
maya.elena08@icloud.com
a_todosijevic@hotmail.com
hbt47@yahoo.com
dahliatop@gmail.com
vtortella@gmail.com
hj_mackay@yahoo.com
dm_tortorelli@yahoo.com
zacha26@yahoo.com
meltravers@yahoo.com
trinity9909@gmail.com
chintan.tripathi@gmail.com
tubba.ali@gmail.com
peterdtynan@gmail.com
asmauddin@gmail.com
shahzad_usmani@hotmail.com
liuila2525@gmail.com
sahraeyans@gmail.com
tessiekusjes@gmail.com
smritijee@gmail.com
martaviegas40@gmail.com
e_vilardo@aol.com
adriana@avpconsulting.com
sara.vogelhut@bms.com
kelizp@gmail.com
sonawadhwa@yahoo.com
tobywahl@gmail.com
alexandra.g.walker@gmail.com
alicedowwalker@yahoo.com
wildehope5@gmail.com
zuhairah.scott@gmail.com
kdeye@yahoo.com
jgwelch00@gmail.com
cynthia.hens@gmail.com
sherryjwheeler@yahoo.com
emma_whelan@yahoo.com
emidori5@gmail.com
katyawhite@gmail.com
lwides@msn.com
mmthaemert@mac.com
bonitajo@gmail.com
saraselterw@gmail.com
mwilliams8510@outlook.com
coslislo@comcast.net
kathleen.n.wolf@gmail.com
amanda.lawrence.wood@gmail.com
capitolcaroline@gmail.com
heatherbworley@yahoo.com
barrieyallof@verizon.net
nabeela1@aol.com
ayelaman72@hotmail.com
malorenayg@gmail.com
simonyohannes44@gmail.com
mikiyoshimura3@gmail.com
ayounoszai@gmail.com
kateyounoszai@icloud.com
yousra@gmail.com
adzettler@gmail.com
attiyeh@hotmail.com
pzoido@gmail.com
thegreekbutterfly@gmail.com
szughayer@gmail.com
aczulueta@gmail.com`;

function extractEmailsToSet(emailString: string): Set<string> {
    const emailArray = emailString
      .split('\n')                 // Split by new lines
      .map(email => email.trim())  // Remove any leading/trailing spaces
      .filter(email => email);     // Remove empty lines if any
  
    return new Set(emailArray);
}

export const clients2025F: Set<string> = extractEmailsToSet(client2025FList);